# SQLite version 3.x
# gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
  adapter: postgresql
  encoding: utf-8
  database: oonek_dev
  pool: 5
  username: postgres
  password: maisa
  host: localhost
  port: 5432 

production:
  adapter: postgresql
  encoding: utf-8
  database: oonek_prod
  pool: 5
  username: postgres
